#!/usr/bin/python3 
import cv2
import numpy as np

image = cv2.imread("logo.png", 0)

#griye çevirmek için 0 kullandık. Kanallarını kullanmak istemediğimizi belirttik. RGB fonksiyonu görmek için 0 silmemiz yeterli
#ekranda gösterme fonksiyonu : imshow
cv2.imshow("industrial engineer", image)

#matrixleri terminalde görmek için resmi print yapmak gerekir.
print(image)
#boyutları görmek için 
print(image.size)
#hangi veri tipinde yazıldığını görmek için, her bir piksel 8 bitte yazılır, 0 ile 255 arası pixel değişiklği olur.
# {1,1,1,1,1,1} = 2^7 + 2^6 + 2^5 + 2^4 + 2^3 + 2^2 + 2^1 + 2^0 = 255
print(image.dtype)
#genişliğini, yüksekliğini ve kaç kanal kullanıldığını göster.
print(image.shape)
#yazdıralım ve yeni oluşturduğumuz resmi kaydedelim
cv2.imwrite("newgraduate.png", image)


#kapanışta kullanmamız gerek temel bir iskelet, pencere kapanması için herhangi bir tuşa basmanız yeterli
cv2.waitKey(0)
#tüm sekmeleri kapatır
cv2.destroyALLWindows()
